### ISSUE TITLE
gallium.live throwing WebSocket connection exception

### ISSUE THREAD

**Issue by nasser** [sleexyz/gallium#109]
Visiting `http://gallium.live/` throws

```
bundle.6de1183c3d6846953bbf.js:34 WebSocket connection to 'ws://localhost:58121/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
(anonymous) @ bundle.6de1183c3d6846953bbf.js:34
bundle.6de1183c3d6846953bbf.js:34 Could not connect to ws://localhost:58121
```

**Comment by sleexyz** [comment]
Yes, we should delete the websocket part; it's not used for anything and it confuses people into thinking some part of it is broken. This was a holdover from back when I was experimenting for a performance in January.

Trying hard not to merge too many one-off hacks just for performances :))
