### ISSUE TITLE
Invert Doesn't work anymore 

### ISSUE THREAD

**Issue by jaredlynchart** [sleexyz/gallium#97]
:((

**Comment by sleexyz** [comment]
works for me. does it work in private browsing for you?

**Comment by sleexyz** [comment]
@jaredlynchart just remembered we never fix this problem yesterday. Can you post  your chrome version/osx version?

**Comment by jaredlynchart** [comment]
Absolutely.
Chrome: Version 65.0.3325.181 (Official Build) (64-bit)
OSX: High Sierra (10.13)

**Comment by sleexyz** [comment]
@jaredlynchart should be fixed now

**Comment by jaredlynchart** [comment]
indeed it does. thanks!
